
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Xuan Tang
 * the CreateTaskDialog class is a Graphical User Interface class that is a 
 * dialog allowing a user to enter information to create a new Task object.
 */
public class CreateTaskDialog extends javax.swing.JFrame {
    private MainFrame mainFrame;
    private TaskLists theTaskLists;
    private Task theTask;
    private JTable theToDoTable;

    /**
     * Default constructor
     */
    public CreateTaskDialog() {
        initComponents();
    }
    
    /**
     * Constructor that specifies the MainFrame, the TaskLists, and the To-Do Jtable
     * Initializes the errorLabel to invisible and sets the color of the windows
     * @param mainFrameToAdd
     * @param taskLists
     * @param toDoTable 
     */
    public CreateTaskDialog(MainFrame mainFrameToAdd, TaskLists taskLists, JTable toDoTable){
        
        initComponents();

        mainFrame = mainFrameToAdd;
        theTaskLists = taskLists;
        theToDoTable = toDoTable;
        
        errorLabel.setVisible(false);
        
        this.getContentPane().setBackground(new Color(7,6,24));
        this.getContentPane().setForeground(new Color(7,6,24));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        taskNameLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deadlineLabel = new javax.swing.JTextField();
        prioritySlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        createNewTaskButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Task Details");

        jPanel1.setBackground(new java.awt.Color(2, 0, 26));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(53, 1, 1), new java.awt.Color(14, 4, 4)));

        taskNameLabel.setBackground(new java.awt.Color(23, 9, 34));
        taskNameLabel.setFont(new java.awt.Font("Estrangelo Antioch", 0, 15)); // NOI18N
        taskNameLabel.setForeground(new java.awt.Color(202, 225, 254));

        jLabel1.setFont(new java.awt.Font("Estrangelo Antioch", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 214, 214));
        jLabel1.setText("Task:");

        jLabel2.setFont(new java.awt.Font("Estrangelo Antioch", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 214, 214));
        jLabel2.setText("Deadline:");

        deadlineLabel.setBackground(new java.awt.Color(23, 9, 34));
        deadlineLabel.setFont(new java.awt.Font("Estrangelo Antioch", 0, 15)); // NOI18N
        deadlineLabel.setForeground(new java.awt.Color(202, 225, 254));

        prioritySlider.setMaximum(3);
        prioritySlider.setMinimum(1);
        prioritySlider.setValue(2);

        jLabel3.setFont(new java.awt.Font("Estrangelo Antioch", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 214, 214));
        jLabel3.setText("Priority:");

        createNewTaskButton.setBackground(new java.awt.Color(23, 9, 34));
        createNewTaskButton.setFont(new java.awt.Font("Estrangelo Antioch", 0, 18)); // NOI18N
        createNewTaskButton.setForeground(new java.awt.Color(186, 216, 253));
        createNewTaskButton.setText("Create New Task");
        createNewTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewTaskButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(23, 9, 34));
        cancelButton.setFont(new java.awt.Font("Estrangelo Antioch", 0, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(186, 216, 253));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(193, 245, 255));
        errorLabel.setText("Task name cannot be blank!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deadlineLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(taskNameLabel)
                            .addComponent(prioritySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createNewTaskButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deadlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(prioritySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(createNewTaskButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * the method to run when the cancel button is clicked. it tells the mainframe
     * to refresh its display, and then closes the dialog.
     * @param evt 
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        mainFrame.refreshDisplay();
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    /**
     * the mtehod to run when the create new task button is clicked.
     * it fetches the strings from the text fields and also the value from the 
     * prioirty slider, and uses this information to create a new task.
     * The task isthen added to the To-Do table and also the To-Do list in TaskLists.
     * The dialog is then closed.
     * @param evt 
     */
    private void createNewTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewTaskButtonActionPerformed
        String newTaskName = taskNameLabel.getText();
        String newDeadline = deadlineLabel.getText();
        int newPriority = prioritySlider.getValue();
        if(newTaskName.equals(""))
            errorLabel.setVisible(true);
        else{
            errorLabel.setVisible(false);
            Task theTask = new Task(newTaskName, newDeadline, newPriority);
            theTaskLists.addToDoTask(theTask);
        
            DefaultTableModel m = (DefaultTableModel)theToDoTable.getModel();
            m.addRow(new Object[]{theTask});
            mainFrame.refreshDisplay();
            this.dispose();
        }
        
        
    }//GEN-LAST:event_createNewTaskButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToDoDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToDoDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToDoDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToDoDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToDoDetailsDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createNewTaskButton;
    private javax.swing.JTextField deadlineLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider prioritySlider;
    private javax.swing.JTextField taskNameLabel;
    // End of variables declaration//GEN-END:variables
}
