
import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        mainTitleLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        authenticationErrorLabel = new javax.swing.JLabel();
        userSessionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        toDoScroll = new javax.swing.JScrollPane();
        toDoTable = new javax.swing.JTable();
        inProgressScroll = new javax.swing.JScrollPane();
        inProgressTable = new javax.swing.JTable();
        doneScroll = new javax.swing.JScrollPane();
        doneTable = new javax.swing.JTable();
        createTaskButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Task Management");
        setBackground(new java.awt.Color(255, 0, 0));
        setForeground(new java.awt.Color(248, 28, 28));

        mainPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(20, 10, 10));
        loginPanel.setForeground(new java.awt.Color(193, 176, 176));

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        usernameLabel.setBackground(new java.awt.Color(253, 190, 190));
        usernameLabel.setForeground(new java.awt.Color(253, 190, 190));
        usernameLabel.setText("Username:");

        passwordLabel.setForeground(new java.awt.Color(253, 190, 190));
        passwordLabel.setText("Password:");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        mainTitleLabel.setFont(new java.awt.Font("Estrangelo Antioch", 1, 24)); // NOI18N
        mainTitleLabel.setForeground(new java.awt.Color(253, 190, 190));
        mainTitleLabel.setText("Task Management");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        authenticationErrorLabel.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(passwordField)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(authenticationErrorLabel)
                        .addGap(345, 345, 345))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(mainTitleLabel)
                        .addGap(271, 271, 271))))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(mainTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(27, 27, 27)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(exitButton))
                .addGap(46, 46, 46)
                .addComponent(authenticationErrorLabel)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        mainPanel.add(loginPanel, "card2");

        userSessionPanel.setBackground(new java.awt.Color(7, 6, 24));

        jLabel1.setForeground(new java.awt.Color(251, 180, 243));
        jLabel1.setText("WE're IN! whaaaaaaaaaaat?!");

        toDoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", "To Do"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        toDoTable.setDragEnabled(true);
        toDoTable.getTableHeader().setReorderingAllowed(false);
        toDoScroll.setViewportView(toDoTable);
        if (toDoTable.getColumnModel().getColumnCount() > 0) {
            toDoTable.getColumnModel().getColumn(0).setResizable(false);
            toDoTable.getColumnModel().getColumn(0).setPreferredWidth(2);
            toDoTable.getColumnModel().getColumn(1).setResizable(false);
            toDoTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        inProgressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", "In Progress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        inProgressTable.setDragEnabled(true);
        inProgressTable.getTableHeader().setReorderingAllowed(false);
        inProgressScroll.setViewportView(inProgressTable);
        if (inProgressTable.getColumnModel().getColumnCount() > 0) {
            inProgressTable.getColumnModel().getColumn(0).setResizable(false);
            inProgressTable.getColumnModel().getColumn(0).setPreferredWidth(2);
            inProgressTable.getColumnModel().getColumn(1).setResizable(false);
            inProgressTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        doneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", "Done"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        doneTable.setDragEnabled(true);
        doneTable.getTableHeader().setReorderingAllowed(false);
        doneScroll.setViewportView(doneTable);
        if (doneTable.getColumnModel().getColumnCount() > 0) {
            doneTable.getColumnModel().getColumn(0).setResizable(false);
            doneTable.getColumnModel().getColumn(0).setPreferredWidth(2);
            doneTable.getColumnModel().getColumn(1).setResizable(false);
            doneTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        createTaskButton.setText("Create Task");
        createTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTaskButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("Log Out");

        jButton1.setText("Move Task");

        javax.swing.GroupLayout userSessionPanelLayout = new javax.swing.GroupLayout(userSessionPanel);
        userSessionPanel.setLayout(userSessionPanelLayout);
        userSessionPanelLayout.setHorizontalGroup(
            userSessionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSessionPanelLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addContainerGap(408, Short.MAX_VALUE))
            .addGroup(userSessionPanelLayout.createSequentialGroup()
                .addComponent(toDoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inProgressScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doneScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userSessionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createTaskButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        userSessionPanelLayout.setVerticalGroup(
            userSessionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSessionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userSessionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inProgressScroll)
                    .addComponent(doneScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(toDoScroll)
                    .addGroup(userSessionPanelLayout.createSequentialGroup()
                        .addComponent(createTaskButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOutButton)))
                .addContainerGap())
        );

        mainPanel.add(userSessionPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(795, 554));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        
        String username = usernameTextField.getText();
        String password = new String(passwordField.getPassword());
        try{
                if(authenticate(username, password)){
                    CardLayout cl = (CardLayout)mainPanel.getLayout();
                    cl.next(mainPanel);
                } else{
                    authenticationErrorLabel.setText("Username/Password incorrect");
                }
                    
            }catch(IOException ex){
                System.err.println("fuck if i know wtf is going on!");
            }
    }//GEN-LAST:event_loginButtonActionPerformed

    private boolean authenticate(String username, String password) throws IOException{
        Scanner in = null;
        
        try{
            in = new Scanner(new BufferedReader(new FileReader("usersInfo.txt")));
            boolean found = false;
            String usernameFromFile;
            String passwordFromFile;
            
            if(!in.hasNext()){
                System.err.println("USERNAME FILE EMPTY. EXITING...");
                System.exit(1);
            }
            
            while(!found && in.hasNext()){
                usernameFromFile = in.next();
                if(usernameFromFile.equals(username)){
                    found = true;
                    if(!in.hasNext()){
                        System.err.println("USERNAME FILE FORMAT ERROR. EXITING...");
                        System.exit(1);
                    }
                    passwordFromFile = in.next();
                    if(passwordFromFile.equals(password))
                        return true;
                    else
                        return false;
                }
            }
        }finally{
            if(in!=null)
                in.close();
            else
                System.err.println("USERNAME FILE NEVER OPENED.");
        }
        
        return false;
    }
    
    
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void createTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTaskButtonActionPerformed
        // TODO add your handling code here:
        
        //JOptionPane.showMessageDialog(this, "Excuse me! We do ask that you do not touch anything!","Shame on you!",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_createTaskButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authenticationErrorLabel;
    private javax.swing.JButton createTaskButton;
    private javax.swing.JScrollPane doneScroll;
    private javax.swing.JTable doneTable;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane inProgressScroll;
    private javax.swing.JTable inProgressTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JScrollPane toDoScroll;
    private javax.swing.JTable toDoTable;
    private javax.swing.JPanel userSessionPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
