
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x
 */
public class ToDoDetailsDialog extends javax.swing.JFrame {
    private MainFrame mainFrame;
    private int listType;
    Task theTask;

    /**
     * Creates new form ToDoDetailsDialog
     */
    public ToDoDetailsDialog() {
        initComponents();
    }
    
    public ToDoDetailsDialog(Task task, MainFrame mainFrameToAdd, int theListType){
        
        initComponents();
        //this.setModal (true);
        this.setAlwaysOnTop (true);
        //this.setModalityType (ModalityType.APPLICATION_MODAL);
        theTask = task;
        if(theListType==3)
            moveButton.setVisible(false);
        errorLabel.setVisible(false);
        mainFrame = mainFrameToAdd;
        listType = theListType;
        taskNameLabel.setText(task.getTaskName());
        deadlineLabel.setText(task.getDate());
        prioritySlider.setValue(task.getPriority());
        this.getContentPane().setBackground(new Color(20,5,1));
        //this.getContentPane().setForeground(new Color(20,5,1));
        //this.setDefaultLookAndFeelDecorated(true);
        //AWTUtilities.setWindowOpacity(this, 0.40f);
        //this.setBackground(new Color(0, 0, 0, 0));
        
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        taskNameLabel = new javax.swing.JTextField();
        deadlineLabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prioritySlider = new javax.swing.JSlider();
        closeButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        moveButton = new javax.swing.JButton();
        saveChangesButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setTitle("Task Details");

        jPanel1.setBackground(new java.awt.Color(24, 3, 8));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(14, 2, 53), new java.awt.Color(16, 2, 2)));

        jLabel1.setFont(new java.awt.Font("Estrangelo Antioch", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 214, 214));
        jLabel1.setText("Task::");

        taskNameLabel.setBackground(new java.awt.Color(37, 1, 7));
        taskNameLabel.setForeground(new java.awt.Color(253, 211, 211));

        deadlineLabel.setBackground(new java.awt.Color(37, 1, 7));
        deadlineLabel.setForeground(new java.awt.Color(253, 211, 211));

        jLabel2.setFont(new java.awt.Font("Estrangelo Antioch", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 214, 214));
        jLabel2.setText("Deadline:");

        jLabel3.setFont(new java.awt.Font("Estrangelo Antioch", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 214, 214));
        jLabel3.setText("Priority:");

        prioritySlider.setBackground(new java.awt.Color(11, 1, 37));
        prioritySlider.setForeground(new java.awt.Color(41, 1, 1));
        prioritySlider.setMaximum(3);
        prioritySlider.setMinimum(1);

        closeButton.setBackground(new java.awt.Color(15, 4, 8));
        closeButton.setFont(new java.awt.Font("Estrangelo Antioch", 0, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(253, 185, 254));
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(15, 4, 8));
        deleteButton.setFont(new java.awt.Font("Estrangelo Antioch", 0, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(253, 185, 254));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        moveButton.setBackground(new java.awt.Color(15, 4, 8));
        moveButton.setFont(new java.awt.Font("Estrangelo Antioch", 0, 18)); // NOI18N
        moveButton.setForeground(new java.awt.Color(253, 185, 254));
        moveButton.setText("Move");
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });

        saveChangesButton.setBackground(new java.awt.Color(15, 4, 8));
        saveChangesButton.setFont(new java.awt.Font("Estrangelo Antioch", 0, 18)); // NOI18N
        saveChangesButton.setForeground(new java.awt.Color(253, 185, 254));
        saveChangesButton.setText("Save Changes");
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(254, 221, 221));
        errorLabel.setText("Task name cannot be blank!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(moveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(deadlineLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(taskNameLabel)
                                .addComponent(prioritySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deadlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(prioritySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveButton)
                    .addComponent(closeButton)
                    .addComponent(deleteButton))
                .addGap(30, 30, 30)
                .addComponent(saveChangesButton)
                .addGap(18, 18, 18)
                .addComponent(errorLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        mainFrame.refreshDisplay();
        moveButton.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
        if(listType == 1)
            mainFrame.moveToDoToInProg();
        else if(listType == 2)
            mainFrame.moveInProgToDone();

        mainFrame.refreshDisplay();
        this.dispose();
    }//GEN-LAST:event_moveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        mainFrame.deleteTask(listType);
        mainFrame.refreshDisplay();
        this.dispose();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        String newTaskName = taskNameLabel.getText();
        String newDeadline = deadlineLabel.getText();
        int newPriority = prioritySlider.getValue();
        
        if(newTaskName.equals(""))
            errorLabel.setVisible(true);
        else{
                errorLabel.setVisible(false);
                theTask.setTaskName(newTaskName);
                theTask.setDate(newDeadline);
                theTask.setPriority(newPriority);
            }
        
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToDoDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToDoDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToDoDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToDoDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToDoDetailsDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField deadlineLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton moveButton;
    private javax.swing.JSlider prioritySlider;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JTextField taskNameLabel;
    // End of variables declaration//GEN-END:variables
}
